### ISSUE TITLE
Remove COINBASE_FLAGS

### ISSUE THREAD

**Issue by jnewbery** [jnewbery/bitcoin#7]
Defined here: https://github.com/jnewbery/bitcoin/blob/edb6b768a4185a4aaa6281ee50a6538f7426cb1e/src/validation.cpp#L133

See where it was added and why it is no longer used.

**Comment by maflcko** [comment]
Sounds like a miner left-over?

**Comment by maflcko** [comment]
d449772cf69c01932fc5d72c46054815d6300b3c

**Comment by jnewbery** [comment]
Correct!
