### ISSUE TITLE
Turn the global mempool into a shared pointer

### ISSUE THREAD

**Issue by jnewbery** [jnewbery/bitcoin#8]
Global mempool is defined here: https://github.com/bitcoin/bitcoin/blob/8237889e8d0fb7542669a9098516c96da91913f0/src/validation.cpp#L130

It should be changed to a shared pointer (and renamed `g_mempool`) so that it isn't initialized until runtime. That would allow us to remove the code added in https://github.com/bitcoin/bitcoin/pull/6889.

**Comment by maflcko** [comment]
Have you seen #17407 ?

Also, it should probably be a unique ptr to keep everyone sane

**Comment by jnewbery** [comment]
D'oh. Yes I even commented on it. Big concept ACK!
